### ISSUE TITLE
BUG: Code block rendering error

### ISSUE THREAD

**Issue by ghost** [theme-particlex/hexo-theme-particlex#100]
如图所示
![图片](https://github.com/theme-particlex/hexo-theme-particlex/assets/66206988/cec2ebf3-2bff-40ed-b2fb-43c632f20280)

似乎是 hexo 及其某些依赖项的版本升级导致了这个问题
如果使用旧版本的heox及其依赖，大概就不会出现这个问题

**Comment by SaltedFishesNG** [comment]
该错误仅出现于当 `package.json` 的 `"hexo": "^7.0.0"` 时会发生，若版本为6.3.0则不会出现

解决方法：修改_config.yml为以下值
```
syntax_highlighter: /js/lib/highlight.js
highlight:
  enable: false
prismjs:
  enable: false
```
