### ISSUE TITLE
关于不同的主页路由设置

### ISSUE THREAD

**Issue by linkedlist771** [theme-particlex/hexo-theme-particlex#78]
作者您好！ 很感谢您所做的主题页面，给我带来了很大的帮助，这里我想询问一下，在您的readme中
```
bash 
/about
    Archives:
        name: box-archive
        theme: solid
        link: /archives
    Categories:
        name: bookmark
        theme: solid
        link: /categories
    Tags:
        name: tags
        theme: solid
        link: /tags
```
这些路由是怎么设置的，谢谢。
